### ISSUE TITLE
Problem with hitting button (Modifier Keys) in control menu, as well as crashing when hitting CTRL + Shift

### ISSUE THREAD

**Issue by Zanderwrob** [Zanderwrob/APFOC#3]
<details>
  <summary>Log</summary>

[17:24:56] [main/INFO]: [STDOUT]: Minimap session finalized.
[17:24:57] [main/INFO]: Stopping worker threads
[17:24:58] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:625) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: grondag.fermion.modkeys.ModKeysConfigScreen.method_27534(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Lnet/minecraft/class_5348;III)V
	at grondag.fermion.modkeys.ModKeysConfigScreen.method_25394(ModKeysConfigScreen.java:94) ~[2a0aa4e7-622e-4beb-ac62-efdf66d0a23d.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:616) ~[intermediary-minecraft-1.16.4-client.jar:?]
	... 18 more
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 1/5/21 5:24 PM
Description: Rendering screen

java.lang.NoSuchMethodError: grondag.fermion.modkeys.ModKeysConfigScreen.method_27534(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Lnet/minecraft/class_5348;III)V
	at grondag.fermion.modkeys.ModKeysConfigScreen.method_25394(ModKeysConfigScreen.java:94)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at grondag.fermion.modkeys.ModKeysConfigScreen.method_25394(ModKeysConfigScreen.java:94)

-- Screen render details --
Details:
	Screen name: grondag.fermion.modkeys.ModKeysConfigScreen
	Mouse location: Scaled: (408, 26). Absolute: (1226.296021, 77.825073)
	Screen size: Scaled: (480, 263). Absolute: (2880, 1574). Scale factor of 6.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['MrZanMan'/166, l='ClientLevel', x=-250.89, y=59.00, z=-199.52]]
	Chunk stats: SodiumChunkCache: 272
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,63,-256), Chunk: (at 0,3,0 in -15,-16; contains blocks -240,0,-256 to -225,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 34597 game time, 34597 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 592194160 bytes (564 MB) / 1653080064 bytes (1576 MB) up to 3262644224 bytes (3111 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms350m -Xmx3500m
	Fabric Mods: 
		architectury: Architectury 1.2.68
		artifice: Artifice 0.14.4+1.16.3
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		blade: Blade 2.0.0
		blockus: Blockus 2.0.2+1.16.4
		byg: BYG 1.1.3
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-block: Cardinal Components API (blocks) 2.6.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		cardinal-components-level: Cardinal Components API (world saves) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		charm: Charm 2.2.2
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compact-storage: CompactStorage 4.1.0
		dankstorage: Dank Storage 1.9a-1.16.3
		fabric: Fabric API 0.29.2+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		glassential: Glassential 1.16.4-1.1.5
		goml: Get Off My Lawn 1.1.0
		harvest: Harvest 1.2.12
		healthoverlay: Health Overlay 3.6.13
		illuminations: Illuminations 1.4
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 1.3.1-1.16.2
		iron-jetpacks: Iron Jetpacks 0.2.6
		itemscroller: Item Scroller 0.15.0-dev.20201103.183933
		jankson: Jankson 3.0.1+j1.2.0
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.6.1-BETA
		kubejs: KubeJS 1.5.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.3-pre.3
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.6.1
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		magna: Magna 1.4.3-1.16.2
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.13+build.19
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_joml_joml: joml 1.9.25
		patchouli: Patchouli 1.16.2-44-FABRIC
		phosphor: Phosphor 0.7.0+build.10
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		sandwichable: Sandwichable 1.1.2
		shapes: Shapes 2.0.0+build.10
		simplevoidworld: Simple Void World 4.0.0
		sodium: Sodium 0.1.0
		team_reborn_energy: Energy 0.1.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		universalcomponents: Universal Components 0.7.3+1.16.2
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		waila: Hwyla 1.9.22
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.30.1
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(TM) Plus Graphics 645 GL version 2.1 INTEL-16.0.49, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
#@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Contents/MacOS/instances/Fabric Tester 1.16.4/.minecraft/crash-reports/crash-2021-01-05_17.24.58-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

</details>

**Comment by Zanderwrob** [comment]
Any time I hit the Ctrl + Shift buttons in any of the menus it crashes

Disabling Mod Menu
